version: '2'
services:
  myNodeApp:
    image: node
    container_name: servicio_rest_node
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command: npm start server/server
  mongodb:
    image: mongo
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
    volumes:
      - /c/Users/neo12/Documents/Dockers/mongodb/data:/data
    ports:
      - 27017:27017
    command: mongod --logpath=/data/log # --quiet  
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongodb
